# Generated by Django 3.1.5 on 2021-03-30 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=50)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(max_length=80)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('link', models.CharField(max_length=200)),
                ('approved_by', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=8192)),
            ],
        ),
    ]
